//! Coverage 19 — `src/cli/packages/install/arch.rs` + `update/arch.rs`
//!
//! Contracts pinned (all through the real binary, no unit reimplementation):
//!
//! 1. `try_local_package_name`: installing a local `*.pkg.tar.*` file records
//!    package history under the package name parsed from *inside* the archive
//!    via ALPM, with source "local".
//! 2. `try_local_package_name` error path: an unreadable/corrupt archive falls
//!    back to recording the raw file path so history never loses the operation.
//! 3. Deferred-sync arm in `update/arch.rs`: when a non-root process performs a
//!    real update with official updates pending, the elevated child owns the
//!    official history changes; the parent records an Update transaction with
//!    success=false and ZERO change entries.
//! 4. `--check` updates never elevate and never record history.
//! 5. An update with nothing pending takes neither the privileged arm nor the
//!    history-recording path.
#![cfg(feature = "arch")]

pub mod common;

use common::*;

use flate2::Compression;
use flate2::write::GzEncoder;
use std::fs;
use std::path::{Path, PathBuf};
use tar::{Builder, EntryType, Header};

/// Write a minimal gzip-compressed tar containing a `.PKGINFO` entry (modern
/// `key = value` layout, as written by makepkg 7.x) that libalpm's `pkg_load`
/// accepts.
fn write_fake_package(path: &Path, name: &str, version: &str) {
    let pkginfo = format!(
        "# Generated by coverage_19\npkgname = {name}\npkgbase = {name}\nxdata = pkgtype=pkg\npkgver = {version}\npkgdesc = fake package for coverage_19\nurl = https://example.invalid/\nbuilddate = 1700000000\npackager = coverage_19 <cov19@example.invalid>\nsize = 4096\narch = x86_64\nlicense = MIT\n"
    );

    let file = fs::File::create(path).expect("create fake package file");
    let mut encoder = GzEncoder::new(file, Compression::default());
    {
        let mut builder = Builder::new(&mut encoder);

        let mut header = Header::new_gnu();
        header.set_path(".PKGINFO").expect("valid entry path");
        header.set_size(pkginfo.len() as u64);
        header.set_entry_type(EntryType::Regular);
        header.set_mode(0o644);
        header.set_cksum();
        builder
            .append(&header, pkginfo.as_bytes())
            .expect("append .PKGINFO");

        builder.finish().expect("finish archive");
    }
    let file = encoder.finish().expect("finish gzip");
    file.sync_all().expect("flush");
}

/// Write bytes that are NOT a valid gzip stream but keep the package
/// extension, so `pkg_load` must fail while `canonicalize` succeeds.
fn write_corrupt_package(path: &Path) {
    fs::write(path, b"this is definitely not gzip or tar payload")
        .expect("write corrupt package file");
}

/// Create the minimal filesystem layout libalpm expects under the harness
/// pacman root before `open_default_alpm` runs inside the child process.
fn prepare_pacman_root(project: &TestProject) {
    for dir in ["var/lib/pacman/local", "var/lib/pacman/sync"] {
        fs::create_dir_all(project.pacman_root.path().join(dir))
            .expect("create pacman root layout");
    }
}

fn history_path(project: &TestProject) -> PathBuf {
    project.data_dir.path().join("history.json")
}

/// Load the isolated data dir's history.json (a JSON array of transactions).
fn load_history(project: &TestProject) -> Vec<serde_json::Value> {
    let raw = fs::read_to_string(history_path(project)).expect("history.json must exist after run");
    serde_json::from_str(&raw).expect("history.json must be a valid JSON array")
}

/// ---------------------------------------------------------------------------
/// Contract 1 + 2: try_local_package_name via install history
/// ---------------------------------------------------------------------------

#[test]
fn local_package_history_records_the_name_parsed_from_inside_the_archive() {
    let project = TestProject::for_distro("arch");
    prepare_pacman_root(&project);

    // A filename-derived identity must disagree with the .PKGINFO identity.
    let pkg_path = project.path().join("decoytool-1.2.3-4-x86_64.pkg.tar.gz");
    write_fake_package(&pkg_path, "faketesttool", "9.9.9-1");
    let path_arg = pkg_path.to_str().expect("utf8 temp path");

    // The mock repo does not know this absolute path, so pm.install rejects it
    // and the install fails — but history MUST still be recorded, under the
    // name read from inside the archive by try_local_package_name.
    let result = project.run(&["install", path_arg, "--allow-local-file", "--yes"]);
    result.assert_failure();
    result.assert_stderr_contains("not found in any repository");

    let history = load_history(&project);
    assert_eq!(
        history.len(),
        1,
        "exactly one transaction recorded, got: {history:?}"
    );
    assert_eq!(history[0]["transaction_type"].as_str(), Some("Install"));
    assert_eq!(history[0]["success"].as_bool(), Some(false));

    let changes = history[0]["changes"].as_array().expect("changes array");
    assert_eq!(changes.len(), 1, "one change per requested package");
    assert_eq!(
        changes[0]["name"].as_str(),
        Some("faketesttool"),
        "history must record faketesttool from .PKGINFO, not decoytool from the filename or the raw path"
    );
    assert_eq!(changes[0]["source"].as_str(), Some("local"));
}

#[test]
fn unreadable_local_archive_falls_back_to_recording_the_raw_path() {
    let project = TestProject::for_distro("arch");
    prepare_pacman_root(&project);

    let pkg_path = project.path().join("corrupttool-1.0-1-x86_64.pkg.tar.gz");
    write_corrupt_package(&pkg_path);
    let path_arg = pkg_path.to_str().expect("utf8 temp path");

    let result = project.run(&["install", path_arg, "--allow-local-file", "--yes"]);
    result.assert_failure();

    let history = load_history(&project);
    assert_eq!(history.len(), 1);
    assert_eq!(history[0]["transaction_type"].as_str(), Some("Install"));
    assert_eq!(history[0]["success"].as_bool(), Some(false));

    let changes = history[0]["changes"].as_array().expect("changes array");
    assert_eq!(changes.len(), 1);
    assert_eq!(
        changes[0]["name"].as_str(),
        Some(path_arg),
        "when ALPM cannot read the archive metadata, history must fall back to \
         the raw requested path instead of dropping or renaming the change"
    );
    assert_eq!(changes[0]["source"].as_str(), Some("local"));
}

/// ---------------------------------------------------------------------------
/// Contract 3: deferred-sync arm of update/arch.rs
/// ---------------------------------------------------------------------------

#[test]
fn deferred_sync_update_delegates_official_work_and_parent_records_no_changes() {
    if omg_lib::core::privilege::is_root() {
        report_skip("deferred-sync parent/child split only applies to non-root callers");
        return;
    }

    let project = TestProject::for_distro("arch");

    // One installed package has a newer version available in the mock repo.
    project.mock_install("pkgA", "1.0").expect("seed installed");
    project
        .mock_available("pkgA", "2.0")
        .expect("seed available");

    // Non-root + not check-only + not dry-run => needs_deferred_sync is true.
    // In dev/test mode elevation bails out with this exact diagnostic before
    // touching sudo, which lets us observe the arm deterministically.
    let result = project.run(&["update", "--yes"]);
    result.assert_failure();
    result.assert_stderr_contains("Privilege elevation not supported in development mode");

    // Single-ownership rule: the official upgrade was delegated to the child,
    // so THIS process must record an Update transaction with zero changes —
    // otherwise every official package would appear twice once both sides log.
    let history = load_history(&project);
    assert_eq!(
        history.len(),
        1,
        "exactly one Update transaction recorded, got: {history:?}"
    );
    assert_eq!(history[0]["transaction_type"].as_str(), Some("Update"));
    assert_eq!(history[0]["success"].as_bool(), Some(false));
    let changes = history[0]["changes"].as_array().expect("changes array");
    assert!(
        changes.is_empty(),
        "delegated official changes must NOT be parent-recorded, got: {changes:?}"
    );
}

/// ---------------------------------------------------------------------------
/// Contracts 4 + 5: arms that must NOT engage
/// ---------------------------------------------------------------------------

#[test]
fn check_only_update_never_writes_history() {
    if omg_lib::core::privilege::is_root() {
        report_skip("deferred-sync parent/child split only applies to non-root callers");
        return;
    }

    let project = TestProject::for_distro("arch");
    project.mock_install("pkgA", "1.0").expect("seed installed");
    project
        .mock_available("pkgA", "2.0")
        .expect("seed available");

    let result = project.run(&["update", "--check"]);
    result.assert_success();
    result.assert_stdout_contains("omg update");

    assert!(
        !history_path(&project).exists(),
        "--check may refresh databases but must return before any history recording happens"
    );
}

#[test]
fn update_with_no_pending_updates_takes_no_privileged_or_history_path() {
    let project = TestProject::for_distro("arch");

    // Nothing seeded => list_updates is empty.
    let result = project.run(&["update", "--yes"]);
    result.assert_success();
    result.assert_stdout_contains("System is up to date");

    assert!(
        !history_path(&project).exists(),
        "an up-to-date system must not produce an Update transaction"
    );
}
