[package]
name = "omg-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
libfuzzer-sys = "0.4"
omg_lib = { path = ".." }

[[bin]]
name = "parse_config"
path = "fuzz_targets/parse_config.rs"
test = false
doc = false

[[bin]]
name = "ipc_messages"
path = "fuzz_targets/ipc_messages.rs"
test = false
doc = false

[[bin]]
name = "package_names"
path = "fuzz_targets/package_names.rs"
test = false
doc = false
