[store]
dir = "target/nextest"

[profile.default]
test-threads = "num-cpus"
fail-fast = true
status-level = "pass"
final-status-level = "fail"
retries = 1

[profile.ci]
test-threads = "num-cpus"
fail-fast = false
status-level = "all"
final-status-level = "all"
retries = { backoff = "exponential", count = 2, delay = "1s", jitter = true }
slow-timeout = { period = "60s", terminate-after = 3 }

[profile.ci-junit]
test-threads = "num-cpus"
fail-fast = false
retries = { backoff = "exponential", count = 2, delay = "1s", jitter = true }
slow-timeout = { period = "60s", terminate-after = 3 }

[profile.ci-junit.junit]
path = "target/nextest/junit.xml"
report-name = "omg-tests"

[profile.dev]
test-threads = 4
fail-fast = true
status-level = "pass"
retries = 0

[profile.heavy]
test-threads = 2
fail-fast = false
retries = 1
slow-timeout = { period = "120s", terminate-after = 2 }
