#!/usr/bin/env bash
# Generate release notes for a specific version to stdout.
# Usage: ./scripts/gen-release-notes.sh <version>
#
# Single source of truth for release notes: consumed by release.yml (tag
# pushes and manual publishes). The verification section MUST stay in sync
# with how artifacts are actually published and attested:
#   - archives + .sha256 sidecars → GitHub Releases
#   - SLSA build provenance attestations → GitHub artifacts API
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <version>" >&2
  exit 64
fi

version="$1"
semver_re='^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$'
if [[ ! "$version" =~ $semver_re ]]; then
  echo "invalid release version: $version" >&2
  exit 65
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cat <<EOF_HEADER
## Alpha

OMG is alpha software: the CLI, flags, and on-disk formats can change without a compatibility guarantee.

## Breaking changes

These CLI and release changes shipped in 0.1.215 and remain in later alphas.

### \`omg license\` removed

Local features are no longer license-gated. Dashboard identity is optional.

\`\`\`bash
# Removed
omg license
omg license check
omg license pricing

# Use instead
omg account status
omg account link <token>
omg account unlink
\`\`\`

Team, Enterprise, and Fleet commands no longer require a paid JWT. Scripts that expected those commands to fail without a license will now succeed locally. Remote dashboard sync still needs a valid token from \`omg account link\`.

## Installation

**Quick Install (Linux/macOS):**
\`\`\`bash
curl -fsSL https://omg.latham.cloud/install.sh | bash
\`\`\`

**Windows Subsystem for Linux:** Use the Linux installer inside your WSL distribution.

EOF_HEADER

echo ""
echo "## What's New in v${version}"
echo ""

if "$script_dir/extract-release-notes.sh" "${version}"; then
  echo "✓ Extracted changelog for v${version}" >&2
else
  echo "⚠ No changelog found, using generic message" >&2
  echo "See [full changelog](https://github.com/PyRo1121/omg/blob/main/docs/changelog.md) for details."
fi

cat <<EOF_FOOTER

---

## Platform Support

| Platform | Architecture | Binary |
|----------|--------------|--------|
| Arch Linux | x86_64 | \`omg-v${version}-x86_64-linux-arch.tar.gz\` |
| Debian | x86_64 | \`omg-v${version}-x86_64-linux-debian.tar.gz\` |
| Ubuntu | x86_64 | \`omg-v${version}-x86_64-linux-ubuntu.tar.gz\` |
| Fedora/RHEL | x86_64 | \`omg-v${version}-x86_64-linux-fedora.tar.gz\` |
| macOS | ARM64 | \`omg-v${version}-aarch64-darwin.tar.gz\` |
| WSL | x86_64 | Use the binary matching the installed Linux distribution |

## Verification

Verify the downloaded archive before extracting or installing it.

**Integrity (checksum):**

**Linux:**
\`\`\`bash
sha256sum -c omg-v${version}-*.sha256
\`\`\`

**macOS:**
\`\`\`bash
shasum -a 256 -c omg-v${version}-*.sha256
\`\`\`

**Provenance (recommended):** every release archive carries a Sigstore build
provenance attestation generated by GitHub Actions. Verify it with the GitHub
CLI:

\`\`\`bash
gh attestation verify omg-v${version}-x86_64-linux-arch.tar.gz -R PyRo1121/omg
\`\`\`

\`omg self-update\` and \`install.sh\` perform this check automatically whenever
the GitHub CLI is installed locally.

## Manual Installation

**Linux/macOS:**
\`\`\`bash
tar -xzf omg-v${version}-*.tar.gz
cd omg-v${version}-*
sudo cp omg /usr/local/bin/
\`\`\`

---

**Full Changelog**: https://github.com/PyRo1121/omg/blob/main/docs/changelog.md
EOF_FOOTER